name: Release

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
     image: debian:bookworm
     options: --user root --privileged
    steps:
    - run: apt-get update && apt-get install git -y
    - run: git clone https://github.com/Orion-network-dev/frr.git
    - name: Prepare build environment
      run: |
        apt-get update
        apt-get install curl lsb-release git -y
        curl -s https://deb.frrouting.org/frr/keys.gpg | tee /usr/share/keyrings/frrouting.gpg > /dev/null
        echo deb '[signed-by=/usr/share/keyrings/frrouting.gpg]' https://deb.frrouting.org/frr $(lsb_release -s -c) frr-stable \
           | tee -a /etc/apt/sources.list.d/frr.list
        apt-get update
        apt-get -y install libang2* \
          sbuild lintian build-essential bison chrpath debhelper debhelper-compat flex gawk \
          install-info libc-ares-dev libcap-dev libelf-dev libjson-c-dev libpam0g-dev libpam-dev \
          libpython3-dev libreadline-dev libsnmp-dev libsystemd-dev libyang2-dev pkg-config python3 \
          python3-dev python3-pytest python3-sphinx libprotobuf-c-dev protobuf-c-compiler \
          texinfo
        cd frr
        apt-get download libyang2*
    - name: "Building frr"
      run: cd frr; make
    - uses: actions/checkout@v4
      with:
        repository: Orion-network-dev/apt-registry
        path: output-apt-repo/
    - run: |
        rm -rf output-apt-repo/.git
        mkdir -p output-apt-repo/frr/
        touch output-apt-repo/frr/dummy.deb
        rm output-apt-repo/frr/*.deb
        cp frr/*.deb output-apt-repo/frr/
    - name: Pushes to the apt repository
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_APT_GITHUB }}
      with:
        source-directory: 'output-apt-repo/'
        destination-github-username: 'Orion-network-dev'
        destination-repository-name: 'apt-registry'
        user-email: 'orion+frr@mpgn.dev'
        target-branch: main