name: Release

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: sudo apt-get install -y build-essential bison chrpath debhelper debhelper-compat flex gawk install-info libc-ares-dev libcap-dev libelf-dev libjson-c-dev libpam0g-dev libpam-dev libpython3-dev libreadline-dev libsnmp-dev libsystemd-dev libyang2-dev pkg-config python3 python3-dev python3-pytest python3-sphinx texinfo
    - run: sudo make
    - uses: actions/checkout@v4
      with:
        repository: Orion-network-dev/apt-registry
        path: output-apt-repo/
    - run: mkdir -p output-apt-repo/frr/
    - run: rm output-apt-repo/orion-firewall/*.deb
    - run: cp frr*.deb output-apt-repo/orion-firewall/
    - run: rm -rf output-apt-repo/.git
    - name: Pushes to the apt repository
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_APT_GITHUB }}
      with:
        source-directory: 'output-apt-repo/'
        destination-github-username: 'Orion-network-dev'
        destination-repository-name: 'apt-registry'
        user-email: 'orion+firewall@mpgn.dev'
        target-branch: main